version: 0.2  
phases:  
  install:
    commands:
      - aws cloudformation package --template-file search-photos.yaml --s3-bucket lambda-deployement-pipeline-bucketi --output-template-file search-new.yaml
artifacts:  
  type: yaml
  files:
    - search-photos.yaml